### ISSUE TITLE
Feature Request: Add referrer link support for URL

### ISSUE THREAD

**Issue by bawzz234** [nates/ProxyChecker#6]
Hi Nate, 

It has been a while, hope you're well?

I found there are URLs that require a referrer link to be able to access the site. Or it may need to have requirements on header response/request. Is it possible to add this feature?

Looking forward to hear from you.

Best Regards

**Comment by nates** [comment]
Hello, long time no see bawzz. I'm not sure that I understand your issue, could you elaborate some more?

**Comment by bawzz234** [comment]
Hi Nate, 

Sorry for the late response, was away for a while. 

Something is like adding info from HTTP header request/response from a site, like for example: 

User agent:
adding an option to change user agent like -useragent="Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"

Sometime site requires referer to access the site, which is found under request headers:
-referer=site url here

Although, these options aren't really much needed for most sites, I encountered with one site that wasn't working with the checker which probably required referral url or different user agent. For example, this site for some reason didn't work:  https://ipinfo.io/

This feature is really very optional, you can skip it if you don't have much time. 

I did have another feature request in mind, which is adding IP address recognition for URL. 

There are some sites that require an IP for example:
https://www.abuseipdb.com/check/64.233.191.255

So something like this in url (**url=https://www.abuseipdb.com/check/{ip}**) to add the proxy's IP there for checking.

Also, sometime this error was showing when checking any site, It kept on going in command line and had to force close it. I managed to copy the errors:

`goroutine 14183 [select, 7 minutes]:
net.(*Resolver).lookupIPAddr(0x831d20, {0x6af570, 0xc0001060d8}, {0x651505, 0xc009db9818},
 {0xc0034b55c0, 0xd})
        C:/Program Files/Go/src/net/lookup.go:302 +0x5c7
net.(*Resolver).LookupIPAddr(...)
        C:/Program Files/Go/src/net/lookup.go:207
net.LookupIP({0xc0034b55c0, 0xc0034b55ce})
        C:/Program Files/Go/src/net/lookup.go:193 +0x4f
h12.io/socks.lookupIPv4({0xc0034b55c0, 0xd})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/net.go:46 +0x27
h12.io/socks.(*config).dialSocks4(0xc0069d1590, {0xc0034b55c0, 0x11})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/socks4.go:31 +0x265
h12.io/socks.(*config).dialFunc.func2({0x496497, 0xc009b23200}, {0xc0034b55c0, 0x60})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/socks.go:81 +0x28
net/http.(*Transport).dial(0xc009b62fc0, {0x6af5a8, 0xc009b62fc0}, {0x6516ce, 0x0}, {0xc00
34b55c0, 0x0})
        C:/Program Files/Go/src/net/http/transport.go:1169 +0x5a
net/http.(*Transport).dialConn(0xc009b4b040, {0x6af5a8, 0xc009b62fc0}, {{}, 0x0, {0xc00010
e0a5, 0x5}, {0xc0034b55c0, 0x11}, 0x0})
        C:/Program Files/Go/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x6aa3a0, 0xc009b56790)
        C:/Program Files/Go/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
        C:/Program Files/Go/src/net/http/transport.go:1415 +0x3d7

goroutine 14305 [select, 7 minutes]:
net.(*Resolver).lookupIPAddr(0x831d20, {0x6af570, 0xc0001060d8}, {0x651505, 0xc009f27818},
 {0xc006c6cbe8, 0xd})
        C:/Program Files/Go/src/net/lookup.go:302 +0x5c7
net.(*Resolver).LookupIPAddr(...)
        C:/Program Files/Go/src/net/lookup.go:207
net.LookupIP({0xc006c6cbe8, 0xc006c6cbf6})
        C:/Program Files/Go/src/net/lookup.go:193 +0x4f
h12.io/socks.lookupIPv4({0xc006c6cbe8, 0xd})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/net.go:46 +0x27
h12.io/socks.(*config).dialSocks4(0xc006ff9dd0, {0xc006c6cbe8, 0x11})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/socks4.go:31 +0x265
h12.io/socks.(*config).dialFunc.func2({0x496497, 0xc009dc8a20}, {0xc006c6cbe8, 0x60})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/socks.go:81 +0x28
net/http.(*Transport).dial(0xc009deeea0, {0x6af5a8, 0xc009deeea0}, {0x6516ce, 0x0}, {0xc00
6c6cbe8, 0x0})
        C:/Program Files/Go/src/net/http/transport.go:1169 +0x5a
net/http.(*Transport).dialConn(0xc009c65e00, {0x6af5a8, 0xc009deeea0}, {{}, 0x0, {0xc00010
e0a5, 0x5}, {0xc006c6cbe8, 0x11}, 0x0})
        C:/Program Files/Go/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x6aa3a0, 0xc009d80c60)
        C:/Program Files/Go/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
        C:/Program Files/Go/src/net/http/transport.go:1415 +0x3d7

goroutine 22358 [runnable, locked to thread]:
syscall.Syscall6(0x7ffd15812600, 0x6, 0x2, 0x1, 0x0, 0x0, 0x0, 0x81)
        C:/Program Files/Go/src/runtime/syscall_windows.go:`

Thank you so much for working hard on this checker. I have used plenty of programs, in my experience, "examiner" is the best proxy checker I have every used. 

Best Regards

**Comment by nates** [comment]
I see, I will look into the error.

**Comment by bawzz234** [comment]
Hi Nates,

I hope you are well. It has been a while, but the error it is showing is more constant than before:

goroutine 5842 [select, 9 minutes]:
net.(*Resolver).lookupIPAddr(0x831d20, {0x6af570, 0xc00009e110}, {0x651505, 0xc004c0f818},
 {0xc0030ef470, 0xf})
        C:/Program Files/Go/src/net/lookup.go:302 +0x5c7
net.(*Resolver).LookupIPAddr(...)
        C:/Program Files/Go/src/net/lookup.go:207
net.LookupIP({0xc0030ef470, 0xc0030ef480})
        C:/Program Files/Go/src/net/lookup.go:193 +0x4f
h12.io/socks.lookupIPv4({0xc0030ef470, 0xf})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/net.go:46 +0x27
h12.io/socks.(*config).dialSocks4(0xc003a8f6b0, {0xc0030ef470, 0x13})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/socks4.go:31 +0x265
h12.io/socks.(*config).dialFunc.func2({0x496497, 0xc0048559e0}, {0xc0030ef470, 0x60})
        C:/Users/Administrator/go/pkg/mod/h12.io/socks@v1.0.3/socks.go:81 +0x28
net/http.(*Transport).dial(0xc004af0180, {0x6af5a8, 0xc004af0180}, {0x6516ce, 0x0}, {0xc00
30ef470, 0x0})


when this error shows, it doesn't exit the cmdline and when forced closed, the result/working proxies weren't saved. Please give it a look when you get some time. 

Best Regards
